---
- name: Install VSFTPd ftp server
  apt:
    name: vsftpd
    update_cache: true
    state: present

- name: Enable IPv4 listener (independent of inetd)
  replace:
    path: /etc/vsftpd.conf
    regexp: 'listen=NO'
    replace: 'listen=YES'
  notify: 'Restart VSFTPd'

- name: Disable IPv6 listener
  replace:
    path: /etc/vsftpd.conf
    regexp: 'listen_ipv6=YES'
    replace: 'listen_ipv6=NO'
  notify: 'Restart VSFTPd'

- name: Enable and start VSFTPd
  service:
    name: vsftpd
    enabled: yes
    state: started
      # Problems with PID checking lead to false positives on startup errors: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=754762;msg=9
  ignore_errors: yes
